###
@url=http://localhost:8080
###
@baseUrl=http://localhost:8080/api/v1
### Test
GET {{url}}/checkStatus


### Set key
PUT {{baseUrl}}/user
Content-Type: application/json

{
    "key": "b",
    "payload": "b"
}


### Get key
POST {{baseUrl}}/users
Content-Type: application/json

{
    "key": "b"
}


### GET all user
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE0NTE4NjFkY2UzZGVlYjIxNTQ1ZDciLCJpYXQiOjE2OTU4MzM0MTMsImV4cCI6MTY5NTgzMzQ0M30.mFyvOgIbnN8DdCFJDyE68R_qXIFPD64osZrwRWqTd_Q


### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "Thang1",
    "email": "thangla2013@gmail.com",
    "password": "11111111"
}


### Verify otp
POST {{baseUrl}}/auth/verifyOtp
Content-Type: application/json

{
    "username": "Thang1",
    "email": "thangla2013@gmail.com",
    "password": "11111111",
    "otp": "751563"
}


### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "Thangla",
    "password": "11111111"
}