###
@url=http://localhost:8080
###
@baseUrl=http://localhost:8080/api/v1
### Test
GET {{url}}/checkStatus


### Set key
PUT {{baseUrl}}/user
Content-Type: application/json

{
    "key": "b",
    "payload": "b"
}


### Get key
POST {{baseUrl}}/users
Content-Type: application/json

{
    "key": "b"
}


### GET all user
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE0NTE4NjFkY2UzZGVlYjIxNTQ1ZDciLCJpYXQiOjE2OTU4ODcyNjAsImV4cCI6MTY5NTg4NzI5MH0.UPERSIBwBc6xGVd2w2AiutZQI_1TZCw31u41MGlt_xE


### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "Thang1",
    "email": "thangla2013@gmail.com",
    "password": "11111111"
}


### Verify otp
POST {{baseUrl}}/auth/verifyOtp
Content-Type: application/json

{
    "username": "Thang1",
    "email": "thangla2013@gmail.com",
    "password": "11111111",
    "otp": "751563"
}


### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "Thangla",
    "password": "11111111"
}


### Refresh token
POST {{baseUrl}}/auth/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE0NTE4NjFkY2UzZGVlYjIxNTQ1ZDciLCJpYXQiOjE2OTU5NjMzMzcsImV4cCI6MTcyNzUyMDkzN30.bdchxlRSI6-ozsxX-GeMG9Bixz25grn19atbl95jszs"
}
